s = "Python is portable and platform independent language. It is programmer friendly language."
print("Performing operations on",s)
print("-"*100)
print("|"*100)
print("-"*100)
print("1. All letters of string in capital letters ->\t",s.upper())
print("*"*100)
print("2. All letters of string in small letters ->\t",s.lower())
print("*"*100)
print("3. First letter of string in capital letter ->\t",s.capitalize())
print("*"*100)
print("4. First letter of all words in string in capital letter ->\t",s.title())
print("*"*100)
print("5. Length of string ->\t",len(s))
print("*"*100)
print("6. Count number of 'a' in string ->\t",s.count('a'))
print("*"*100)
print("7. What's the index of letter 'a' ->\t",s.index('a'))
print("*"*100)
print("8. Finding 'ytho' in string ->\t",s.find('ytho'))
print("*"*100)
print("9. Checking that all letter of string is in lower case or not ->\t",s.islower())
print("*"*100)
print("10. Checking that all letter of string is in upper case or not ->\t",s.upper())
print("*"*100)
print("11. Checking that is their any space or not ->\t",s.isspace())
print("*"*100)
print("12. Checking that all characters of string are letters or not ->\t",s.isalpha())
print("*"*100)
print("13. Checking that all characters of string are digits or not ->\t",s.isdigit())
print("*"*100)
print("14. Printing starting 5 letters including spaces ->\t",s[0:5])
print("*"*100)
print("15. Print substring using index from 10 to 25 having a gap of 2 ->\t",s[10:26:2])
print("*"*100)
print("16. Print substring using index from 1 to 90 having a gap of 10 ->\t",s[1:90:10])
print("*"*100)
print("17. Removing all leading spaces ->\t",s.lstrip())
print("*"*100)
print("18. Removing all trailing spaces ->\t",s.rstrip())
print("*"*100)
print("19. Removing all leading and trailing spaces ->\t",s.strip())
print("*"*100)
print("20. Replace 'a' by 'z' ->\t",s.replace('a','z'))
print("*"*100)